import { createFileRoute } from "@tanstack/react-router";
import { Wand2, Clapperboard, Film, Sparkles, Layers, UserCheck } from "lucide-react";
import { ServiceDetail } from "@/components/dravonix/ServiceDetail";
import { buildHead, breadcrumbSchema, faqSchema, serviceSchema } from "@/lib/seo";

const title = "AI Video & Design Studio in Kerala, India | Dravonix Media";
const description =
  "AI-powered video production and creative design from Dravonix Media — promotional videos, social reels, motion graphics and product visuals, with human creative supervision.";

const faqs = [
  {
    q: "Is the work fully generated by AI?",
    a: "No. AI accelerates editing, iteration and asset generation. Creative direction, brand judgement and final quality control are always handled by our team.",
  },
  {
    q: "What formats do you deliver?",
    a: "Promotional videos, social media reels, motion graphics, product visuals and ad creative, exported for each platform's required aspect ratios.",
  },
  {
    q: "How fast is turnaround?",
    a: "Faster than a traditional edit pipeline because iteration is cheaper — exact timelines depend on scope and are confirmed in your proposal.",
  },
  {
    q: "Will the output still look on-brand?",
    a: "Yes. We work from your brand guidelines, and every deliverable passes human review before it reaches you.",
  },
];

export const Route = createFileRoute("/ai-studio")({
  head: () =>
    buildHead("/ai-studio", {
      title,
      description,
      schemas: [
        serviceSchema({
          name: "AI Video and Creative Production",
          description,
          path: "/ai-studio",
        }),
        breadcrumbSchema([
          { name: "Home", path: "/" },
          { name: "Services", path: "/services" },
          { name: "AI-Integrated Video & Design", path: "/ai-studio" },
        ]),
        faqSchema(faqs),
      ],
    }),
  component: AiStudioPage,
});

const services = [
  {
    icon: Clapperboard,
    title: "AI-Assisted Video Production",
    desc: "Concept to final cut, accelerated by AI tooling without giving up creative control.",
  },
  {
    icon: Sparkles,
    title: "Creative Direction",
    desc: "Idea, script, tone and visual language shaped around your brand before a frame is made.",
  },
  {
    icon: Film,
    title: "Promotional Videos & Reels",
    desc: "Short-form social reels and brand films built for the platforms your audience actually uses.",
  },
  {
    icon: Layers,
    title: "Motion Graphics",
    desc: "Animated titles, transitions and explainers that make a message easier to follow.",
  },
  {
    icon: Wand2,
    title: "Product Visuals & AI Editing",
    desc: "Clean product imagery and AI-assisted edits produced at speed and at scale.",
  },
  {
    icon: UserCheck,
    title: "Human Quality Control",
    desc: "Every deliverable reviewed by a human for brand accuracy, pacing and finish.",
  },
];

const steps = [
  { title: "Brief", desc: "Understanding the message, audience and platform." },
  { title: "Concept", desc: "Script, storyboard and creative direction." },
  { title: "Produce", desc: "AI-assisted production, editing and motion work." },
  { title: "Review & Deliver", desc: "Human quality control, revisions and final exports." },
];

const audience = [
  "Brands that need a steady volume of video without a steady studio cost.",
  "Businesses launching products that need visuals fast.",
  "Teams running paid campaigns that burn through creative.",
  "Companies that want modern production without losing brand craft.",
];

const benefits = [
  "More creative variations for the same budget.",
  "Faster turnaround between concept and publish.",
  "Consistent brand look across every asset.",
  "Ad creative you can test and iterate quickly.",
];

function AiStudioPage() {
  return (
    <ServiceDetail
      eyebrow="AI Video & Design"
      breadcrumbLabel="AI-Integrated Video & Design"
      title="AI-Powered Video and Creative Production"
      subtitle="Dravonix Media combines AI-assisted production with human creative direction — delivering promotional videos, social reels, motion graphics and product visuals at speed, on brand."
      primaryCta="Start Your Creative Project"
      estimateCta="Get a Creative Estimate"
      services={services}
      steps={steps}
      audience={audience}
      benefits={benefits}
      faqs={faqs}
      related={[
        { label: "Social Media Management", to: "/social-media-management" },
        { label: "Performance Marketing", to: "/performance-marketing" },
        { label: "Brand Identity", to: "/brand-identity" },
        { label: "See our work", to: "/work" },
      ]}
      ctaTitle="Ready to Produce More, Faster?"
      ctaSubtitle="Let's build a creative pipeline that keeps up with your marketing."
    />
  );
}
