/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as WebsiteDevelopmentRouteImport } from './routes/website-development'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SocialMediaManagementRouteImport } from './routes/social-media-management'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SeoRouteImport } from './routes/seo'
import { Route as ProjectEstimatorRouteImport } from './routes/project-estimator'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as PerformanceMarketingRouteImport } from './routes/performance-marketing'
import { Route as HomeRouteImport } from './routes/home'
import { Route as EcommerceDevelopmentRouteImport } from './routes/ecommerce-development'
import { Route as CustomWebApplicationsRouteImport } from './routes/custom-web-applications'
import { Route as CrmBusinessAutomationRouteImport } from './routes/crm-business-automation'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BusinessEmailSetupRouteImport } from './routes/business-email-setup'
import { Route as BrandIdentityRouteImport } from './routes/brand-identity'
import { Route as AiStudioRouteImport } from './routes/ai-studio'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocationsIndexRouteImport } from './routes/locations.index'
import { Route as LocationsUnitedKingdomRouteImport } from './routes/locations.united-kingdom'
import { Route as LocationsUaeRouteImport } from './routes/locations.uae'
import { Route as LocationsKeralaRouteImport } from './routes/locations.kerala'
import { Route as LocationsIndiaRouteImport } from './routes/locations.india'
import { Route as LocationsGlobalRouteImport } from './routes/locations.global'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEnquiriesRouteImport } from './routes/admin.enquiries'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const WebsiteDevelopmentRoute = WebsiteDevelopmentRouteImport.update({
  id: '/website-development',
  path: '/website-development',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialMediaManagementRoute = SocialMediaManagementRouteImport.update({
  id: '/social-media-management',
  path: '/social-media-management',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SeoRoute = SeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectEstimatorRoute = ProjectEstimatorRouteImport.update({
  id: '/project-estimator',
  path: '/project-estimator',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMarketingRoute = PerformanceMarketingRouteImport.update({
  id: '/performance-marketing',
  path: '/performance-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const EcommerceDevelopmentRoute = EcommerceDevelopmentRouteImport.update({
  id: '/ecommerce-development',
  path: '/ecommerce-development',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomWebApplicationsRoute = CustomWebApplicationsRouteImport.update({
  id: '/custom-web-applications',
  path: '/custom-web-applications',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmBusinessAutomationRoute = CrmBusinessAutomationRouteImport.update({
  id: '/crm-business-automation',
  path: '/crm-business-automation',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BusinessEmailSetupRoute = BusinessEmailSetupRouteImport.update({
  id: '/business-email-setup',
  path: '/business-email-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIdentityRoute = BrandIdentityRouteImport.update({
  id: '/brand-identity',
  path: '/brand-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const AiStudioRoute = AiStudioRouteImport.update({
  id: '/ai-studio',
  path: '/ai-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndexRoute = LocationsIndexRouteImport.update({
  id: '/locations/',
  path: '/locations/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsUnitedKingdomRoute = LocationsUnitedKingdomRouteImport.update({
  id: '/locations/united-kingdom',
  path: '/locations/united-kingdom',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsUaeRoute = LocationsUaeRouteImport.update({
  id: '/locations/uae',
  path: '/locations/uae',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsKeralaRoute = LocationsKeralaRouteImport.update({
  id: '/locations/kerala',
  path: '/locations/kerala',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsIndiaRoute = LocationsIndiaRouteImport.update({
  id: '/locations/india',
  path: '/locations/india',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsGlobalRoute = LocationsGlobalRouteImport.update({
  id: '/locations/global',
  path: '/locations/global',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEnquiriesRoute = AdminEnquiriesRouteImport.update({
  id: '/admin/enquiries',
  path: '/admin/enquiries',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-studio': typeof AiStudioRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/business-email-setup': typeof BusinessEmailSetupRoute
  '/contact': typeof ContactRoute
  '/crm-business-automation': typeof CrmBusinessAutomationRoute
  '/custom-web-applications': typeof CustomWebApplicationsRoute
  '/ecommerce-development': typeof EcommerceDevelopmentRoute
  '/home': typeof HomeRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/project-estimator': typeof ProjectEstimatorRoute
  '/seo': typeof SeoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-management': typeof SocialMediaManagementRoute
  '/team': typeof TeamRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/website-development': typeof WebsiteDevelopmentRoute
  '/work': typeof WorkRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/locations/global': typeof LocationsGlobalRoute
  '/locations/india': typeof LocationsIndiaRoute
  '/locations/kerala': typeof LocationsKeralaRoute
  '/locations/uae': typeof LocationsUaeRoute
  '/locations/united-kingdom': typeof LocationsUnitedKingdomRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-studio': typeof AiStudioRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/business-email-setup': typeof BusinessEmailSetupRoute
  '/contact': typeof ContactRoute
  '/crm-business-automation': typeof CrmBusinessAutomationRoute
  '/custom-web-applications': typeof CustomWebApplicationsRoute
  '/ecommerce-development': typeof EcommerceDevelopmentRoute
  '/home': typeof HomeRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/project-estimator': typeof ProjectEstimatorRoute
  '/seo': typeof SeoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-management': typeof SocialMediaManagementRoute
  '/team': typeof TeamRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/website-development': typeof WebsiteDevelopmentRoute
  '/work': typeof WorkRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/locations/global': typeof LocationsGlobalRoute
  '/locations/india': typeof LocationsIndiaRoute
  '/locations/kerala': typeof LocationsKeralaRoute
  '/locations/uae': typeof LocationsUaeRoute
  '/locations/united-kingdom': typeof LocationsUnitedKingdomRoute
  '/locations': typeof LocationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/ai-studio': typeof AiStudioRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/business-email-setup': typeof BusinessEmailSetupRoute
  '/contact': typeof ContactRoute
  '/crm-business-automation': typeof CrmBusinessAutomationRoute
  '/custom-web-applications': typeof CustomWebApplicationsRoute
  '/ecommerce-development': typeof EcommerceDevelopmentRoute
  '/home': typeof HomeRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/process': typeof ProcessRoute
  '/project-estimator': typeof ProjectEstimatorRoute
  '/seo': typeof SeoRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/social-media-management': typeof SocialMediaManagementRoute
  '/team': typeof TeamRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/website-development': typeof WebsiteDevelopmentRoute
  '/work': typeof WorkRoute
  '/admin/enquiries': typeof AdminEnquiriesRoute
  '/admin/login': typeof AdminLoginRoute
  '/locations/global': typeof LocationsGlobalRoute
  '/locations/india': typeof LocationsIndiaRoute
  '/locations/kerala': typeof LocationsKeralaRoute
  '/locations/uae': typeof LocationsUaeRoute
  '/locations/united-kingdom': typeof LocationsUnitedKingdomRoute
  '/locations/': typeof LocationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/ai-studio'
    | '/brand-identity'
    | '/business-email-setup'
    | '/contact'
    | '/crm-business-automation'
    | '/custom-web-applications'
    | '/ecommerce-development'
    | '/home'
    | '/performance-marketing'
    | '/privacy-policy'
    | '/process'
    | '/project-estimator'
    | '/seo'
    | '/services'
    | '/sitemap.xml'
    | '/social-media-management'
    | '/team'
    | '/terms-and-conditions'
    | '/website-development'
    | '/work'
    | '/admin/enquiries'
    | '/admin/login'
    | '/locations/global'
    | '/locations/india'
    | '/locations/kerala'
    | '/locations/uae'
    | '/locations/united-kingdom'
    | '/locations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/ai-studio'
    | '/brand-identity'
    | '/business-email-setup'
    | '/contact'
    | '/crm-business-automation'
    | '/custom-web-applications'
    | '/ecommerce-development'
    | '/home'
    | '/performance-marketing'
    | '/privacy-policy'
    | '/process'
    | '/project-estimator'
    | '/seo'
    | '/services'
    | '/sitemap.xml'
    | '/social-media-management'
    | '/team'
    | '/terms-and-conditions'
    | '/website-development'
    | '/work'
    | '/admin/enquiries'
    | '/admin/login'
    | '/locations/global'
    | '/locations/india'
    | '/locations/kerala'
    | '/locations/uae'
    | '/locations/united-kingdom'
    | '/locations'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/ai-studio'
    | '/brand-identity'
    | '/business-email-setup'
    | '/contact'
    | '/crm-business-automation'
    | '/custom-web-applications'
    | '/ecommerce-development'
    | '/home'
    | '/performance-marketing'
    | '/privacy-policy'
    | '/process'
    | '/project-estimator'
    | '/seo'
    | '/services'
    | '/sitemap.xml'
    | '/social-media-management'
    | '/team'
    | '/terms-and-conditions'
    | '/website-development'
    | '/work'
    | '/admin/enquiries'
    | '/admin/login'
    | '/locations/global'
    | '/locations/india'
    | '/locations/kerala'
    | '/locations/uae'
    | '/locations/united-kingdom'
    | '/locations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AiStudioRoute: typeof AiStudioRoute
  BrandIdentityRoute: typeof BrandIdentityRoute
  BusinessEmailSetupRoute: typeof BusinessEmailSetupRoute
  ContactRoute: typeof ContactRoute
  CrmBusinessAutomationRoute: typeof CrmBusinessAutomationRoute
  CustomWebApplicationsRoute: typeof CustomWebApplicationsRoute
  EcommerceDevelopmentRoute: typeof EcommerceDevelopmentRoute
  HomeRoute: typeof HomeRoute
  PerformanceMarketingRoute: typeof PerformanceMarketingRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  ProcessRoute: typeof ProcessRoute
  ProjectEstimatorRoute: typeof ProjectEstimatorRoute
  SeoRoute: typeof SeoRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SocialMediaManagementRoute: typeof SocialMediaManagementRoute
  TeamRoute: typeof TeamRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  WebsiteDevelopmentRoute: typeof WebsiteDevelopmentRoute
  WorkRoute: typeof WorkRoute
  AdminEnquiriesRoute: typeof AdminEnquiriesRoute
  AdminLoginRoute: typeof AdminLoginRoute
  LocationsGlobalRoute: typeof LocationsGlobalRoute
  LocationsIndiaRoute: typeof LocationsIndiaRoute
  LocationsKeralaRoute: typeof LocationsKeralaRoute
  LocationsUaeRoute: typeof LocationsUaeRoute
  LocationsUnitedKingdomRoute: typeof LocationsUnitedKingdomRoute
  LocationsIndexRoute: typeof LocationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/website-development': {
      id: '/website-development'
      path: '/website-development'
      fullPath: '/website-development'
      preLoaderRoute: typeof WebsiteDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/social-media-management': {
      id: '/social-media-management'
      path: '/social-media-management'
      fullPath: '/social-media-management'
      preLoaderRoute: typeof SocialMediaManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seo': {
      id: '/seo'
      path: '/seo'
      fullPath: '/seo'
      preLoaderRoute: typeof SeoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/project-estimator': {
      id: '/project-estimator'
      path: '/project-estimator'
      fullPath: '/project-estimator'
      preLoaderRoute: typeof ProjectEstimatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-marketing': {
      id: '/performance-marketing'
      path: '/performance-marketing'
      fullPath: '/performance-marketing'
      preLoaderRoute: typeof PerformanceMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecommerce-development': {
      id: '/ecommerce-development'
      path: '/ecommerce-development'
      fullPath: '/ecommerce-development'
      preLoaderRoute: typeof EcommerceDevelopmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custom-web-applications': {
      id: '/custom-web-applications'
      path: '/custom-web-applications'
      fullPath: '/custom-web-applications'
      preLoaderRoute: typeof CustomWebApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm-business-automation': {
      id: '/crm-business-automation'
      path: '/crm-business-automation'
      fullPath: '/crm-business-automation'
      preLoaderRoute: typeof CrmBusinessAutomationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/business-email-setup': {
      id: '/business-email-setup'
      path: '/business-email-setup'
      fullPath: '/business-email-setup'
      preLoaderRoute: typeof BusinessEmailSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-identity': {
      id: '/brand-identity'
      path: '/brand-identity'
      fullPath: '/brand-identity'
      preLoaderRoute: typeof BrandIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-studio': {
      id: '/ai-studio'
      path: '/ai-studio'
      fullPath: '/ai-studio'
      preLoaderRoute: typeof AiStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/': {
      id: '/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof LocationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/united-kingdom': {
      id: '/locations/united-kingdom'
      path: '/locations/united-kingdom'
      fullPath: '/locations/united-kingdom'
      preLoaderRoute: typeof LocationsUnitedKingdomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/uae': {
      id: '/locations/uae'
      path: '/locations/uae'
      fullPath: '/locations/uae'
      preLoaderRoute: typeof LocationsUaeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/kerala': {
      id: '/locations/kerala'
      path: '/locations/kerala'
      fullPath: '/locations/kerala'
      preLoaderRoute: typeof LocationsKeralaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/india': {
      id: '/locations/india'
      path: '/locations/india'
      fullPath: '/locations/india'
      preLoaderRoute: typeof LocationsIndiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/global': {
      id: '/locations/global'
      path: '/locations/global'
      fullPath: '/locations/global'
      preLoaderRoute: typeof LocationsGlobalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/enquiries': {
      id: '/admin/enquiries'
      path: '/admin/enquiries'
      fullPath: '/admin/enquiries'
      preLoaderRoute: typeof AdminEnquiriesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AiStudioRoute: AiStudioRoute,
  BrandIdentityRoute: BrandIdentityRoute,
  BusinessEmailSetupRoute: BusinessEmailSetupRoute,
  ContactRoute: ContactRoute,
  CrmBusinessAutomationRoute: CrmBusinessAutomationRoute,
  CustomWebApplicationsRoute: CustomWebApplicationsRoute,
  EcommerceDevelopmentRoute: EcommerceDevelopmentRoute,
  HomeRoute: HomeRoute,
  PerformanceMarketingRoute: PerformanceMarketingRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  ProcessRoute: ProcessRoute,
  ProjectEstimatorRoute: ProjectEstimatorRoute,
  SeoRoute: SeoRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SocialMediaManagementRoute: SocialMediaManagementRoute,
  TeamRoute: TeamRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  WebsiteDevelopmentRoute: WebsiteDevelopmentRoute,
  WorkRoute: WorkRoute,
  AdminEnquiriesRoute: AdminEnquiriesRoute,
  AdminLoginRoute: AdminLoginRoute,
  LocationsGlobalRoute: LocationsGlobalRoute,
  LocationsIndiaRoute: LocationsIndiaRoute,
  LocationsKeralaRoute: LocationsKeralaRoute,
  LocationsUaeRoute: LocationsUaeRoute,
  LocationsUnitedKingdomRoute: LocationsUnitedKingdomRoute,
  LocationsIndexRoute: LocationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
