/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BrandIdentityRouteImport } from './routes/brand-identity'
import { Route as IndexRouteImport } from './routes/index'

const BrandIdentityRoute = BrandIdentityRouteImport.update({
  id: '/brand-identity',
  path: '/brand-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brand-identity'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brand-identity'
  id: '__root__' | '/' | '/brand-identity'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandIdentityRoute: typeof BrandIdentityRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/brand-identity': {
      id: '/brand-identity'
      path: '/brand-identity'
      fullPath: '/brand-identity'
      preLoaderRoute: typeof BrandIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandIdentityRoute: BrandIdentityRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
