/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SocialMediaManagementRouteImport } from './routes/social-media-management'
import { Route as PerformanceMarketingRouteImport } from './routes/performance-marketing'
import { Route as BrandIdentityRouteImport } from './routes/brand-identity'
import { Route as IndexRouteImport } from './routes/index'

const SocialMediaManagementRoute = SocialMediaManagementRouteImport.update({
  id: '/social-media-management',
  path: '/social-media-management',
  getParentRoute: () => rootRouteImport,
} as any)
const PerformanceMarketingRoute = PerformanceMarketingRouteImport.update({
  id: '/performance-marketing',
  path: '/performance-marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandIdentityRoute = BrandIdentityRouteImport.update({
  id: '/brand-identity',
  path: '/brand-identity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/social-media-management': typeof SocialMediaManagementRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/social-media-management': typeof SocialMediaManagementRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brand-identity': typeof BrandIdentityRoute
  '/performance-marketing': typeof PerformanceMarketingRoute
  '/social-media-management': typeof SocialMediaManagementRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/brand-identity'
    | '/performance-marketing'
    | '/social-media-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/brand-identity'
    | '/performance-marketing'
    | '/social-media-management'
  id:
    | '__root__'
    | '/'
    | '/brand-identity'
    | '/performance-marketing'
    | '/social-media-management'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrandIdentityRoute: typeof BrandIdentityRoute
  PerformanceMarketingRoute: typeof PerformanceMarketingRoute
  SocialMediaManagementRoute: typeof SocialMediaManagementRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/social-media-management': {
      id: '/social-media-management'
      path: '/social-media-management'
      fullPath: '/social-media-management'
      preLoaderRoute: typeof SocialMediaManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/performance-marketing': {
      id: '/performance-marketing'
      path: '/performance-marketing'
      fullPath: '/performance-marketing'
      preLoaderRoute: typeof PerformanceMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand-identity': {
      id: '/brand-identity'
      path: '/brand-identity'
      fullPath: '/brand-identity'
      preLoaderRoute: typeof BrandIdentityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrandIdentityRoute: BrandIdentityRoute,
  PerformanceMarketingRoute: PerformanceMarketingRoute,
  SocialMediaManagementRoute: SocialMediaManagementRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
